sudo: required
dist: trusty
language: java
jdk: oraclejdk8

sudo: required

services:
  docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install


after_success: 
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=veeramani/calculator
  - echo  image name = $IMAGE_NAME commit = $COMMIT
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME